# Финальная сборка
services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    cache:
        image: memcached:1.6-alpine3.19

    web:
        build: .
        entrypoint: ./entrypoint.sh python freelance/manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        environment:
            - DJANGO_SETTINGS_MODULE=core.settings.docker_compose
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        depends_on:
            - db
            - cache
